spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/moonlight
        username: #db-username
        password: #db-password
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        hibernate:
#          ddl-auto: create
    mail:
        host: smtp.gmail.com
        port: 587
        username: #mail-username
        password: #mail-app-password
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
app:
    email:
        sender: #mail-username